### ISSUE TITLE
на странице about не грузится картинка

### ISSUE THREAD

**Issue by cjbars** [Adgam/WEB#3]
там ошибка в пути к картинке

**Comment by Adgam** [comment]
fixed b18c554

**Comment by cjbars** [comment]
правильный путь
`<img src="images/img2.jpg">`

**Comment by Adgam** [comment]
В таком случае придётся папку images перенести в assets. Не могу понять почему у вас не работает, по идеи и у меня не должно работать, раз не правильно но оно работает.

**Comment by cjbars** [comment]
Если написать так "images/img2.jpg" то картинка возьмется из соседней от index.php папки.
Если написать так "/images/img2.php" то картинка возьмется из корневой папки вебсервера. Но эти папки у нас разные. Например у меня полный путь к корню учебных проектов выглядит так /var/www/students/
Твой проект лежит в папке /var/www/students/adgam/
Соответственно если писать со слешем /images... то сервер пойдет искать картинку тут /var/www/students/images/img1.jpg. Но там картинок точно нет.
Если написать с двумя точками то путь для поиска будет таким /var/www/images/img1.jpg туда серверу вообще вход запрещен.
А если написать без слешей то путь до картинки будет /var/www/students/adgam/images/img1.jpg и картинка успешно найдется. Видимо у тебя путь до корня вебсервера совпадает с папкой где лежит проект, поэтому все работает

**Comment by Adgam** [comment]
ааа, так вот оно что) меня просто ещё phpStorm столку сбил, так как говорил, мол не вижу картинки, я и пытался сделать для него корректный путь.
fixed ca1f1d9
