### ISSUE TITLE
метод edit в контроллерах

### ISSUE THREAD

**Issue by cjbars** [Adgam/WEB#6]
похоже что-то не пошло у вас с отправкой данных
сейчас код выглядит так

```
$putdata = file_get_contents('php://input');
$exploded = explode('&', $putdata);
```
но в массиве $putdata должен оказаться JSON массив. А у вас похоже строка в виде url

должно придти так
```
{
   "title":"заголовок",
   "foo":"bar"
}
```
а у вас похоже так
`title=заголовок&foo=bar`

с ангуляром такая штука не прокатит, поэтому надо поправить и подготовиться к приему данных с фронтенда.

**Comment by Adgam** [comment]
fixed 6f50b52
